### ISSUE TITLE
Provide a downloadable extension

### ISSUE THREAD

**Issue by jezdez** [kunklejr/ssl-everywhere.safariextension#1]
I may miss something but I'd love to use this without having to install a bunch of Ruby build dependencies. Would you mind providing a ready-to-install version of the extension?

**Comment by kunklejr** [comment]
We don't offer a pre-built version of the extension for easy installation into Safari because I don't want people to casually install it without realizing it's not completely secure for all sites. Please see https://www.nearinfinity.com/blogs/jeff_kunkle/lessons_learned_building_an_ht.html for details on its shortcomings.

**Comment by jezdez** [comment]
Thanks for clarifying, closing.
